import os
from dotenv import load_dotenv
from groq import Groq
import google.generativeai as genai

load_dotenv()

# --------------------------------------------------
# LLM FALLBACK ROUTER (The "Traffic-Aware" Engine)
# --------------------------------------------------

def _call_llm_with_fallback(messages):
    """
    Tries Gemini models first. If a model hits a traffic error or times out, it switches.
    If Gemini fails entirely, it repeats the exact same logic for Groq.
    """
    
    # 1. Configuration
    groq_models = ["llama3-70b-8192", "mixtral-8x7b-32768", "gemma2-9b-it"]
    groq_keys = [os.getenv(f"GROQ_KEY_{i}") for i in range(1, 5)]

    gemini_models = ["gemini-3.5-flash-lite", "gemini-2.5-flash", "gemini-2.5-flash-lite"]
    gemini_keys = [os.getenv(f"GEMINI_KEY_{i}") for i in range(1, 5)]

    # --- PHASE 1: GEMINI EXECUTION ---
    gemini_messages = []
    system_instruction = None
    
    for msg in messages:
        if msg["role"] == "system":
            system_instruction = msg["content"]
        else:
            role = "model" if msg["role"] == "assistant" else "user"
            gemini_messages.append({"role": role, "parts": [msg["content"]]})

    for model_name in gemini_models:
        for key_idx, key in enumerate(gemini_keys, start=1):
            if not key:
                continue
            try:
                # ---> FIX 1: Log BEFORE the attempt so the console isn't silent
                print(f"🔄 Attempting Gemini: {model_name} (Key {key_idx})...", flush=True)
                
                genai.configure(api_key=key)
                llm = genai.GenerativeModel(
                    model_name=model_name,
                    system_instruction=system_instruction
                )
                
                # ---> FIX 2: Hard 8-second timeout injected here
                response = llm.generate_content(
                    gemini_messages,
                    request_options={"timeout": 8.0}
                )
                
                print(f"✅ SUCCESS: Response generated by {model_name}")
                return response.text
                
            except Exception as e:
                print(f"❌ ERROR on Gemini {model_name}: {e}", flush=True)
                error_msg = str(e).lower()
                if "429" in error_msg or "quota" in error_msg or "rate limit" in error_msg:
                    break # Break out of the key loop, try the next model entirely
                continue

    # --- PHASE 2: GROQ EXECUTION ---
    for model in groq_models:
        for key_idx, key in enumerate(groq_keys, start=1):
            if not key:
                continue
            try:
                # ---> FIX 1: Log BEFORE the attempt
                print(f"🔄 Attempting Groq: {model} (Key {key_idx})...", flush=True)
                
                # ---> FIX 2: Hard 8-second timeout injected here
                client = Groq(api_key=key, timeout=8.0)
                response = client.chat.completions.create(
                    model=model,
                    messages=messages,
                    temperature=0.7,
                    max_tokens=800
                )
                
                print(f"✅ SUCCESS: Response generated by {model}")
                return response.choices[0].message.content
                
            except Exception as e:
                print(f"❌ ERROR on Groq {model}: {e}", flush=True)
                error_msg = str(e).lower()
                if "429" in error_msg or "rate limit" in error_msg or "too many requests" in error_msg:
                    break 
                continue

    # --- PHASE 3: TOTAL FAILURE ---
    raise RuntimeError("CRITICAL ERROR: All Groq and Gemini models/keys exhausted or timed out.")
        
        


# --------------------------------------------------
# CHAT HISTORY PRUNER
# --------------------------------------------------

def prune_chat_history(chat_history, max_messages=8):
    """Keeps the system prompt but prunes old messages to save tokens."""
    if len(chat_history) <= max_messages:
        return chat_history
        
    system_message = chat_history[0]
    remaining = chat_history[1:]
    
    # Keep only the most recent back-and-forth
    remaining = remaining[-(max_messages - 1):]
    return [system_message] + remaining


# --------------------------------------------------
# UNIFIED CHAT & CAMPAIGN GENERATOR
# --------------------------------------------------

def generate_action_response(chat_history: list, cluster_name: str, top_category: str, price_sensitivity: str, user_prompt: str):
    """
    Handles both UI button clicks and raw chat inputs, maintaining context.
    """
    
    # If starting a fresh chat, inject the powerful System Prompt first
    if not chat_history:
        system_prompt = (
    f"You are an elite AI Marketing Strategist. Your current client is focusing on the "
    f"'{cluster_name}' segment"
    + (f", who frequently buy '{top_category}'." if top_category != "General Merchandise" else ".")
    + (f" This segment's discount behavior profile is: '{price_sensitivity}'." if price_sensitivity and price_sensitivity != "None" else "")
    + "\n\n"
    "Rules:\n"
    "1. If asked for a strategy, provide a highly detailed, tactical step-by-step plan (What to do & How to execute it), "
    "grounded in the specific behavioral traits of the segment (e.g., purchase frequency, spend level, engagement, churn risk).\n"
    "2. If asked for copy (email/ads), provide high-converting, personalized text with a hook and CTA.\n"
    "3. Do NOT output fluff like 'Here is your strategy'. Just output the raw requested content formatted cleanly in Markdown.\n"
    "4. Adapt both tone AND tactics to the segment (e.g., high-value/loyal segments get exclusive, reward-driven "
    "approaches; at-risk or dormant segments get urgent, win-back approaches; steady/average segments get "
    "engagement-building approaches).\n"
    + ("5. Use the discount behavior profile to decide whether to include coupon codes or price-based incentives: "
       "if the profile suggests a full-price/non-discount buyer, do NOT include coupon codes or percentage-off offers — "
       "lead with value, exclusivity, or urgency instead. If the profile suggests deal-seeking or promo-driven behavior, "
       "coupon codes and discount framing are appropriate and should be included.\n"
       if price_sensitivity and price_sensitivity != "None" else
       "5. No discount behavior profile was provided — use your best judgment on whether coupon codes or "
       "price-based incentives fit the segment's other traits, without assuming a specific discount preference.\n")
    + ("6. No specific product category was provided — do NOT invent or reference one. Base the entire "
       "strategy purely on the segment's behavioral profile." if top_category == "General Merchandise" else "")
)
        chat_history.append({"role": "system", "content": system_prompt})

    # Only append the user turn if the caller hasn't already added it as the most recent message
    if not chat_history or chat_history[-1]["role"] != "user" or chat_history[-1]["content"] != user_prompt:
        chat_history.append({"role": "user", "content": user_prompt})
    
    # Prune to save context window and avoid token limits
    chat_history = prune_chat_history(chat_history)
    
    # Generate the AI response using the traffic-aware router
    generated_text = _call_llm_with_fallback(chat_history)
    
    # Append the AI's response to maintain conversation memory
    chat_history.append({"role": "assistant", "content": generated_text})
    
    return generated_text, chat_history